/** Patrones para definir las rutas en React Router. */
export const PATHS = {
  home: '/',
  machines: '/maquinas',
  machineNew: '/maquinas/nueva',
  machineDetail: '/maquinas/:id',
  machineEdit: '/maquinas/:id/editar',
  plans: '/mantenimiento',
  planNew: '/mantenimiento/nuevo',
  planDetail: '/mantenimiento/:id',
  planEdit: '/mantenimiento/:id/editar',
  history: '/historial',
  historyDetail: '/historial/:id',
  repairs: '/reparaciones',
  repairNew: '/reparaciones/nueva',
  repairDetail: '/reparaciones/:id',
  repairEdit: '/reparaciones/:id/editar',
  reports: '/reportes',
  alerts: '/alertas',
  settings: '/configuracion',
  notFound: '*',
} as const

/** Constructores de enlaces con id real (para <Link> y navigate). */
export const ROUTES = {
  home: () => '/',
  machines: () => '/maquinas',
  machineNew: () => '/maquinas/nueva',
  machineDetail: (id: string) => `/maquinas/${id}`,
  machineEdit: (id: string) => `/maquinas/${id}/editar`,
  plans: () => '/mantenimiento',
  planNew: () => '/mantenimiento/nuevo',
  planDetail: (id: string) => `/mantenimiento/${id}`,
  planEdit: (id: string) => `/mantenimiento/${id}/editar`,
  history: () => '/historial',
  historyDetail: (id: string) => `/historial/${id}`,
  repairs: () => '/reparaciones',
  repairNew: () => '/reparaciones/nueva',
  repairDetail: (id: string) => `/reparaciones/${id}`,
  repairEdit: (id: string) => `/reparaciones/${id}/editar`,
  reports: () => '/reportes',
  alerts: () => '/alertas',
  settings: () => '/configuracion',
}